language: python
python:
  - "3.6"

stages:
  - lint
  - type
  - tests

install:
  - pip install pipenv
  - make install-dev

jobs:
  include:
    - stage: Quality
      name: lint
      script: make lint
    - name: type
      script: make type
    - name: tests
      script: make test

after_success:
  pipenv run coveralls
